apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  namespace: ui
  labels:
    app: recipe

spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
        - name: angular-server
          image: hemalgadhiya/csye-7374-advanced-cloud-webapp-frontend:93b181c3db7a51c9d899896c8660a5ee18d0ff8f
          ports:
            - containerPort: 2000
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: regcred
