apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  namespace: ui
  labels:
    app: recipe

spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
        - name: angular-server
          image: hemalgadhiya/csye-7374-advanced-cloud-webapp-frontend:29707788d2fc70cd752b0594250e5d2b590c70ea
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
      imagePullSecrets:
        - name: regcred
