apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ui
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFHVnRZV3huWVdSb2FYbGhPa2hvTURjeE1ERTVPVFk9IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy41IChsaW51eCkiCgl9Cn0=

type: kubernetes.io/dockerconfigjson


