apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ui
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFXRnRjR0ZoZG1GdU9uWnBjbUYwUzI5b2JHa3hOVE5BIgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOC4wOS43IChsaW51eCkiCgl9Cn0=
type: kubernetes.io/dockerconfigjson


