apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: ui
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 2000
      targetPort: 2000
  selector:
    app: angular-frontend

  