apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: ui
spec:
  selector:
    app: angular-frontend
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000
  type: LoadBalancer
  